version: "3.8"

services:
  backend:
    build:
      context: sparkling-backend
    ports:
      - "5128:5128"
    volumes:
      - db_data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
      - ./shared-volume:/shared-volume
    networks:
      - appnet
    working_dir: /app
    user: root
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - COMPOSE_DIR=${PWD}
      - ASPNETCORE_URLS=http://+:5128
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_LISTEN_ADDRESS=0.0.0.0
      - ASPNETCORE_PORT=5128
    
    # Fix later, using root in command
    command: >
      /bin/sh -c "
      chown app:app /app/data;
      cd /app && touch /app/data/mydb.db && ln -sf /app/data/mydb.db /app/mydb.db;
      dotnet Sparkling.Backend.dll
      "

  frontend:
    build:
      context: sparkling-frontend
    depends_on:
      - backend
    ports:
      - "80:80"
      - "443:443"
    command: >
      /bin/sh -c "nginx -g 'daemon off;'"
    volumes:
      - ./sparkling-frontend/fullchain.pem:/fullchain.pem
      - ./sparkling-frontend/privkey.pem:/privkey.pem
      - ./sparkling-frontend/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - appnet

networks:
  appnet:
    driver: bridge

volumes:
  db_data:
