version: "3.8"
services:
  backend:
    build:
      context: sparkling-backend
    ports:
      - "5128:5128"
    volumes:
      - db_data:/app/data
    networks:
      - appnet
    working_dir: /app
    user: root # Change user to root for initial setup
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      DEBUG_MODE: "${DEBUG_MODE:-false}" # Set to "true" from terminal to enable development environment, defaults to "false"
    command: >
      /bin/sh -c "
      chown app:app /app/data;
      # Conditional logic for debug mode (development environment)
      if [ \"$DEBUG_MODE\" = \"true\" ]; then
        exec su app -c '
          export ASPNETCORE_ENVIRONMENT=\"Development\";
          export ASPNETCORE_URLS=\"http://*:5128\";
          cd /app && touch /app/data/mydb.db && ln -s /app/data/mydb.db /app/mydb.db; dotnet Sparkling.Backend.dll
        '
      else
        exec su app -c ' # Switch to app user for the rest of the commands
          export ASPNETCORE_ENVIRONMENT=\"Production\";
          export ASPNETCORE_URLS=\"http://*:5128\";
          cd /app && touch /app/data/mydb.db && ln -s /app/data/mydb.db /app/mydb.db; dotnet Sparkling.Backend.dll
        '
      fi
      "

  frontend:
    build:
      context: sparkling-frontend
    depends_on:
      - backend
    ports:
      - "80:80"
      - "443:443"
    command: >
      /bin/sh -c "nginx -g 'daemon off;'"
    volumes:
      - ./sparkling-frontend/fullchain.pem:/fullchain.pem
      - ./sparkling-frontend/privkey.pem:/privkey.pem
      - ./sparkling-frontend/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - appnet

networks:
  appnet:
    driver: bridge

volumes:
  db_data:
