#!/usr/bin/env bash
set -e

trap 'echo "Interrupted, stopping child processes…"; kill 0' SIGINT SIGTERM

cd ./sparkling-frontend || exit
npm run dev &

cd ../sparkling-backend || exit
dotnet run &

wait
